// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// subgroupTEtest
double subgroupTEtest(arma::umat& xu, arma::vec& y, arma::uvec& tr, arma::mat& fx, arma::mat& g, arma::uword B);
RcppExport SEXP _subgroupTEtest_subgroupTEtest(SEXP xuSEXP, SEXP ySEXP, SEXP trSEXP, SEXP fxSEXP, SEXP gSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat& >::type xu(xuSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type tr(trSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type fx(fxSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type g(gSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(subgroupTEtest(xu, y, tr, fx, g, B));
    return rcpp_result_gen;
END_RCPP
}
// subgroupTEtestSurv
double subgroupTEtestSurv(arma::mat& x, arma::umat& xu, arma::vec& y, arma::uvec& dlt, arma::uvec& tr, arma::uword B);
RcppExport SEXP _subgroupTEtest_subgroupTEtestSurv(SEXP xSEXP, SEXP xuSEXP, SEXP ySEXP, SEXP dltSEXP, SEXP trSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::umat& >::type xu(xuSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type dlt(dltSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type tr(trSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(subgroupTEtestSurv(x, xu, y, dlt, tr, B));
    return rcpp_result_gen;
END_RCPP
}
// subgroupTEtestSurv_g
double subgroupTEtestSurv_g(arma::mat& x, arma::umat& xu, arma::vec& y, arma::uvec& dlt, arma::uvec& tr, arma::vec& g, arma::uword B);
RcppExport SEXP _subgroupTEtest_subgroupTEtestSurv_g(SEXP xSEXP, SEXP xuSEXP, SEXP ySEXP, SEXP dltSEXP, SEXP trSEXP, SEXP gSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::umat& >::type xu(xuSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type dlt(dltSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type tr(trSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type g(gSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(subgroupTEtestSurv_g(x, xu, y, dlt, tr, g, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_subgroupTEtest_subgroupTEtest", (DL_FUNC) &_subgroupTEtest_subgroupTEtest, 6},
    {"_subgroupTEtest_subgroupTEtestSurv", (DL_FUNC) &_subgroupTEtest_subgroupTEtestSurv, 6},
    {"_subgroupTEtest_subgroupTEtestSurv_g", (DL_FUNC) &_subgroupTEtest_subgroupTEtestSurv_g, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_subgroupTEtest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
