# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test for uncensored data
#' 
#' 
#' @param xu A matrix of partitions: each column corresponds to a binary partition and each row 
#' corresponds to an observation. 
#' The elements in the matrix must be 1 (group 1) or 2 (group 2). 
#' The element in the ith row and jth column indicates the group membership of the ith observation
#' based on the jth partition.
#' @param y A numeric vector containing the outcome.
#' @param tr A binary vector containing the treatment indicator: 1 - treatment, 0 - control.
#' @param fx A numeric matrix of covariates to be used in f.
#' @param g A vector containing the values of g.
#' @param B An integer of the number of bootstrap samples.
#' @return The p value of the test.
#' @examples
#' set.seed(1)
#' N <- 800
#' beta <- rep(0,length = 50)
#' beta[1] <- 1
#' beta[50] <- -1
#' X <- matrix(rnorm(N*50), ncol = 50)
#' TR <- rbinom(N, 1, 0.5)
#' Y <-  X %*% beta + TR*0.5*(2*(X[,1]>0 | X[,25]>0)-1)+ rnorm(N, sd = 0.5)
#'   
#' # partition matrix
#' X2 <- apply(X,2,function(u) (u<0)+1)
#' # covariates in f
#' X1 <- X[,c(1,25,50)]
#' # p-value (g = 0)
#' subgroupTEtest(X2,Y,TR,X1,rep(0,N),1000)
#' 
#' # estimate g from a working linear model
#' fitg <- lm(Y~X1*TR)
#' G <- cbind(TR,TR*X1) %*% coef(fitg)[5:8]
#' subgroupTEtest(X2,Y,TR,X1,G,1000)
#' @export
subgroupTEtest <- function(xu, y, tr, fx, g, B) {
    .Call(`_subgroupTEtest_subgroupTEtest`, xu, y, tr, fx, g, B)
}

#' Test for censored data (same covariates in f and g). 
#' 
#' The functions f and g use the same pre-specified set of covariates 
#' and are estimated from working AFT models. Note that the follow-up time is on the log scale.
#' 
#' @param x A numeric matrix of covariates to be used in f and g. 
#' @param xu A matrix of partitions: each column corresponds to a binary partition and each row 
#' corresponds to an observation. 
#' The elements in the matrix must be 1 (group 1) or 2 (group 2). 
#' The element in the ith row and jth column indicates the group membership of the ith observation
#' based on the jth partition.
#' @param y A numeric vector containing the follow-up time on the log scale.
#' @param dlt A binary vector containing the event indicator: 1 - event, 0 - censored.
#' @param tr A binary vector containing the treatment indicator: 1 - treatment, 0 - control.
#' @param B An integer of the number of bootstrap samples
#' @return The p value of the test.
#' @examples
#' set.seed(2)
#' N <- 800
#' beta <- rep(0,length = 50)
#' beta[1] <- 1
#' beta[50] <- -1
#' X <- matrix(rnorm(N*50), ncol = 50)
#' TR <- rbinom(N, 1, 0.5)
#' Y0 <-  X %*% beta + TR*0.5*(2*(X[,1]>0 | X[,25]>0)-1)+ rnorm(N, sd = 0.5)
#' Y0 <- as.vector(Y0)
#' C <- log(rexp(N, 0.1))
#' Y <- pmin(Y0,C)
#' DLT <- Y0 <= C
#' X2 <- apply(X,2,function(u) (u<0)+1)
#' # p-value
#' subgroupTEtestSurv(X[,c(1,25,50)], X2, Y, DLT, TR, 1000)
#' subgroupTEtestSurv(X[,c(1,50)], X2, Y, DLT, TR, 1000)
#' @export
subgroupTEtestSurv <- function(x, xu, y, dlt, tr, B) {
    .Call(`_subgroupTEtest_subgroupTEtestSurv`, x, xu, y, dlt, tr, B)
}

#' Test for censored data (user-specified g). 
#' 
#' Users can specify the values of the g function for each observation. 
#' The f function is estimated using a working AFT model. Note that the follow-up time is on the log scale.
#' 
#' @param x A numeric matrix of covariates to be used in f.
#' @param xu A matrix of partitions: each column corresponds to a binary partition and each row 
#' corresponds to an observation. 
#' The elements in the matrix must be 1 (group 1) or 2 (group 2). 
#' The element in the ith row and jth column indicates the group membership of the ith observation
#' based on the jth partition.
#' @param y A numeric vector containing the follow-up time on the log scale.
#' @param dlt A binary vector containing the event indicator: 1 - event, 0 - censored.
#' @param tr A binary vector containing the treatment indicator: 1 - treatment, 0 - control.
#' @param g A vector containing the values of g.
#' @param B An integer of the number of bootstrap samples.
#' @return The p value of the test.
#' @examples
#' set.seed(2)
#' N <- 800
#' beta <- rep(0,length = 50)
#' beta[1] <- 1
#' beta[50] <- -1
#' X <- matrix(rnorm(N*50), ncol = 50)
#' TR <- rbinom(N, 1, 0.5)
#' Y0 <-  X %*% beta + TR*0.5*(2*(X[,1]>0 | X[,25]>0)-1)+ rnorm(N, sd = 0.5)
#' Y0 <- as.vector(Y0)
#' C <- log(rexp(N, 0.1))
#' Y <- pmin(Y0,C)
#' DLT <- Y0 <= C
#' X2 <- apply(X,2,function(u) (u<0)+1)
#' X1 <- X[,c(1,25,50)]
#' # p-value (g = 0)
#' subgroupTEtestSurv_g(X1, X2, Y, DLT, TR, rep(0,N), 1000)
#' 
#' # Estimate g from a working AFT model
#' library(faft)
#' fitg <- faft(Y, DLT, cbind(X1,TR*X1,TR))
#' G <- cbind(TR*X1,TR) %*% fitg$beta[4:7]
#' # p value
#' subgroupTEtestSurv_g(X1, X2, Y, DLT, TR, G, 1000)
#' @export
subgroupTEtestSurv_g <- function(x, xu, y, dlt, tr, g, B) {
    .Call(`_subgroupTEtest_subgroupTEtestSurv_g`, x, xu, y, dlt, tr, g, B)
}

